version: '3.4'

services:
  identityserver:
    image: identityserver
    container_name: identityserver
    build:
      context: ./IdentityServer/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  react:
    image: react
    container_name: react
    build:
      context: ./React/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVER_URL=http://localhost:5000
      - REACT_APP_CLIENT_URL=http://localhost:3000
      - REACT_APP_CLIENT_ID=react.client